[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OpenMS"
authors = [{name = "Zhang, Yu", email = "zhy@lanl.gov"}, {name = "Mazin, Ilia", email = "imazin@lanl.gov"}]
dynamic = ["version", "description"]

[tool.flit.module]
name = "openms"
